const videolinks = [
  {
    id: 1,
    tokenId: 0,
    dropContract: "0xYourDropContractAddressHere",
    src: "https://ipfs.io/ipfs/bafybeiafetfkj75ey5pyuxpvnbfjt6agsp4a2u7wy5py7b2jvvgio3d7em",
    creator: "DJ Hyped Up Reese 🎧",
    cryptoAddy: "0xJerseyClub...",
    tags: ["🔥 Hot Track", "💿 for sale", "Jersey Club"],
    description: "🔥 Jersey Club SZA Remix – A fresh take on the classics!",
    price: "0.05 ETH",
    what3wordsAddress: "club.bounce.jersey",
  },
  {
    id: 2,
    tokenId: 1,
    dropContract: "0xYourDropContractAddressHere",
    src: "https://ipfs.io/ipfs/bafybeihzs44ejbtevneukckela2orjw5ijb4lxpdatniaibmyz7gyuixu4",
    creator: "DJ Hahz 🎤",
    cryptoAddy: "0xJerseyClub...",
    tags: ["🎧 Stream Now", "💿 for sale", "Viral Challenge"],
    description: "🚀 Bring it back – A remix that’s out of this world!",
    price: "0.04 ETH",
    what3wordsAddress: "reel.flash.moment",
  },
  {
    id: 3,
    tokenId: 2,
    dropContract: "0xYourDropContractAddressHere",
    src: "https://ipfs.io/ipfs/bafybeig7pkorh3ilmyh6uekdhqbwc6itqvi7eduirs2y7mhfiwfl3ogpmy",
    creator: "👑 DJ Hahz",
    cryptoAddy: "0xJerseyClub...",
    tags: ["💃 Dance Track", "💿 for sale", "Exclusive"],
    description: "💃 Bounce – Feel the rhythm of the streets!",
    price: "0.06 ETH",
    what3wordsAddress: "party.bounce.rave",
  },
  {
    id: 4,
    tokenId: 3,
    dropContract: "0xYourDropContractAddressHere",
    src: "https://ipfs.io/ipfs/bafybeigzb44h3okzv2hw4xbafremhghbhcfkqcjii7hyt5u2o6iqynds3q",
    creator: "Unclaimed",
    cryptoAddy: "0xJerseyClub...",
    tags: ["🎶 Fresh Drop", "💿 for sale", "Limited Edition"],
    description: "OG Cypher – The true roots of Jersey Club.",
    price: "0.07 ETH",
    what3wordsAddress: "origin.jersey.vibes",
  },
  {
    id: 5,
    tokenId: 4,
    dropContract: "0xYourDropContractAddressHere",
    src: "https://ipfs.io/ipfs/bafybeicmzqkc2fswmybww4ovanjupg3qaiyblbjzwbbucgchajcljph2qm",
    creator: "Brick City 🧱",
    cryptoAddy: "0xJerseyClub...",
    tags: ["🚀 Viral Hit", "💿 for sale", "Jersey Club"],
    description: "🧱 Brick City homage to the original creators of Jersey Club – Respect the roots!",
    price: "0.05 ETH",
    what3wordsAddress: "city.vibe.bounce",
  }
];

export default videolinks;
